apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra-as-code/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ashwanth1109/books
      context: books-msvc
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
