name: Verify
on:
  push:
    branches: [ "**" ]

jobs:
  analyze-books-msvc:
    name: Books Microservice Analysis
    runs-on: ubuntu-latest
    env:
      directory: books-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ${{env.directory}}
        run: npm install
      - name: Lint Books Microservice
        working-directory: ${{env.directory}}
        run: npm run lint
      - name: Tests
        working-directory: ${{env.directory}}
        run: npm run test
  analyze-client:
    name: Client Analysis
    runs-on: ubuntu-latest
    env:
      directory: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ${{env.directory}}
        run: npm install
      - name: Tests
        working-directory: ${{env.directory}}
        run: npm run test
