name: Verify
on:
  push:
    branches: ["**"]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Books Microservice
        working-directory: books-msvc
        run: npm run lint
